<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Bob Ray
 * Date: 8/16/12
 * Time: 11:29 PM
 * To change this template use File | Settings | File Templates.
 */


/**
 * Test class for MyComponentProject Bootstrap.
 * Generated by PHPUnit on 2012-03-02 at 23:02:19.
 * @outputBuffering disabled
 */
class MyComponentProjectTest extends PHPUnit_Framework_TestCase
{
    /* @var $mc MyComponentProject */
    public $mc;
    /* @var $modx modX */
    public $modx;
    /* @var $categoryName string */
    public $categoryName;
    /* @var $utHelpers UtHelpers */
    public $utHelpers;
    /* @var $category modCategory */
    public $category;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before each test is executed.
     */
    protected function setUp()
    {
        // echo "\n---------------- SETUP --------------------";
        require_once dirname(__FILE__) . '/build.config.php';
        require_once dirname(__FILE__) . '/uthelpers.class.php';
        require_once MODX_CORE_PATH . 'model/modx/modx.class.php';
        $this->utHelpers = new UtHelpers();
        $modx = new modX();
        $modx->initialize('mgr');
        $modx->setLogLevel(modX::LOG_LEVEL_ERROR);
        $modx->setLogTarget('ECHO');

        require_once MODX_ASSETS_PATH . 'mycomponents/mycomponent/core/components/mycomponent/model/mycomponent/mycomponentproject.class.php';

        $this->mc = new MyComponentProject($modx, 'unittest.config.php');
        $this->modx =& $this->mc->modx;
        /* @var $categoryObj modCategory */
        $this->category = key($this->mc->props['categories']);
        if ($this->category != 'UnitTest') {
            die('wrong config - NEVER run unit test on a real project!');
        }
        $this->utHelpers->rrmdir($this->mc->targetRoot);
        $this->utHelpers->removeElements($this->modx, $this->mc);
        $this->utHelpers->removeResources($this->modx, $this->mc);
        $category = $this->modx->getCollection('modCategory', array('category' => 'UnitTest'));
        foreach ($category as $categoryObj) {
            $categoryObj->remove();
        }
        $namespace = $this->modx->getObject('modNamespace', array('name' => 'unittest'));
        if ($namespace) $namespace->remove();


        //$this->mc->createCategory();
        //$this->mc->createNamespace();
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after each test is executed.
     */
    protected function tearDown()
    {
        // echo "\n---------------- TEARDOWN --------------------";
        /* @var $categoryObj modCategory */
        /* @var $namespace modNamespace */
        $this->utHelpers->rrmdir($this->mc->targetRoot);
        $category = $this->modx->getCollection('modCategory', array('category' => 'UnitTest'));
        foreach($category as $categoryObj) {
            $categoryObj->remove();
        }
        $namespace = $this->modx->getObject('modNamespace', array('name'=> 'unittest'));
        if ($namespace) $namespace->remove();
        $this->utHelpers->rrmdir($this->mc->targetRoot);
        $this->utHelpers->removeElements($this->modx, $this->mc);
        $this->utHelpers->removeResources($this->modx, $this->mc);
        $this->mc = null;

    }

    /**
     * @covers MyComponentProject::init
     */
    public function testinit()
    {
        /* make sure $modx and $props are set */
        $this->assertTrue(isset($this->mc->modx));
        $this->assertInstanceOf('modX', $this->mc->modx);
        $this->assertTrue(isset($this->mc->props));
        $this->assertTrue(is_array($this->mc->props));

        /* make sure basic member variables are not empty */
        $this->assertNotEmpty($this->mc->packageNameLower);
        $this->assertNotEmpty($this->mc->targetRoot);
        //$this->assertNotEmpty($this->mc->targetAssets);
        $this->assertNotEmpty($this->mc->myPaths['targetCore']);
        $this->assertNotEmpty($this->mc->dirPermission);
        $this->assertNotEmpty($this->mc->props['filePermission']);
        /* make sure helpers class was loaded  */
        $this->assertTrue(method_exists($this->mc->helpers,'replaceTags'));
    }

    public function testCreateCategories() {
        /* @var $category modCategory */
        $this->mc->createCategories();
        $categories = $this->mc->props['categories'];
        $this->assertNotEmpty($categories);
        foreach($categories as $category => $fields){
            $category = $this->modx->getObject('modCategory', array('category' => $category));
            $this->assertInstanceOf('modCategory', $category);
            $p = $category->get('parent');
            if (! empty($p) ) {
                $pObj = $this->modx->GetObject('modCategory', $p);
                $this->assertEquals($fields['parent'], $p->get('category'));
            }
        }


    }
    public function testCreateNamespaces() {
        /* @var $namespace modNamespace */
        $this->mc->createNamespaces();
        $namespace = $this->modx->getObject('modNamespace', array('name' => 'unittest'));
        $this->assertInstanceOf('modNamespace', $namespace);
        $this->assertNotEmpty($namespace->get('path'));
        $this->assertTrue(strstr($namespace->get('path'),'{core_path}') !== false);
        $this->assertTrue(strstr($namespace->get('assets_path'), '{assets_path}') !== false);
        $namespace->remove();

    }

    public function testCreateNewSystemSettings() {
        $this->mc->createNamespaces();
        $this->mc->createNewSystemSettings();
        $settings = $this->mc->props['newSystemSettings'];
        $this->assertNotEmpty($settings);
        /* @var $object modSystemSetting */
        foreach ($settings as $settingKey => $fields) {

            $object = $this->modx->getObject('modSystemSetting', array('key' => $settingKey));
            $this->assertInstanceOf('modSystemSetting', $object);
            $this->assertEquals($this->mc->props['packageNameLower'], $object->get('namespace'));
            $object->remove();
        }

    }
    public function testCreateNewSystemEvents() {
        $this->mc->createNewSystemEvents();
        $events = $this->mc->props['newSystemEvents'];
        $this->assertNotEmpty($events);
        foreach($events as $key => $fields) {
            $object = $this->modx->getObject('modEvent', array('name' => $key));
            $this->assertInstanceOf('modEvent', $object);
            $object->remove();
        }
    }
    public function testCreateElements() {
        /* @var $obj modElement */
        $this->mc->createCategories();
        /* should not create elements */
        $this->mc->props['createElementObjects'] = false;
        $this->mc->props['createElementFiles'] = false;
        $this->mc->createElements();
        $elements = $this->mc->props['elements'];
        $this->assertNotEmpty($elements);
        foreach ($elements as $elementType => $elementNames) {
            $elementType = 'mod' . ucfirst(substr($elementType, 0, -1));
            if (!empty($elementNames)) {
                $alias = $this->mc->helpers->getNameAlias($elementType);
                    foreach ($elementNames as $elementName => $fields) {
                        $obj = $this->modx->getObject($elementType, array($alias => $elementName));
                        //$this->assertNotInstanceOf($elementType,$obj);
                        $fileName = $this->mc->helpers->getFileName($elementName, $elementType);
                        $codeDir = $this->mc->helpers->getCodeDir
                            ($this->mc->myPaths['targetCore'], $elementType);
                        // $this->assertFalse(file_exists($codeDir . '/' . $fileName));
                    }
                }
        }
        /* create files and objects */
        $this->mc->props['createElementObjects'] = true;
        $this->mc->props['createElementFiles'] = true;
        $this->mc->createElements();
        $elements = $this->mc->props['elements'];
        $this->assertNotEmpty($elements);
        foreach ($elements as $elementType => $elementNames) {
            $elementType = 'mod' . ucfirst(substr($elementType, 0, -1));
            if (!empty($elementNames)) {
                $alias = $this->mc->helpers->getNameAlias($elementType);
                foreach ($elementNames as $elementName => $fields) {
                    $obj = $this->modx->getObject($elementType, array($alias => $elementName));
                    $this->assertInstanceOf($elementType, $obj);
                    $fileName = $this->mc->helpers->getFileName($elementName, $elementType);
                    $codeDir = $this->mc->helpers->getCodeDir
                        ($this->mc->myPaths['targetCore'], $elementType);

                    if ($elementType != 'modTemplateVar' && $elementType != 'modPropertySet') {
                        $this->assertTrue(file_exists($codeDir . '/' . $fileName), $fileName . '/' . $fileName);
                    }
                }
            }
        }
        
        $this->utHelpers->RemoveElements($this->modx, $this->mc);
    }
    public function testCreateResources() {
        /* @var $r modResource */
        $this->mc->createCategories();
        $this->mc->createElements();
        $this->mc->createResources();
        $resources = $this->mc->props['resources'];
        $this->assertNotEmpty($resources);
        $id = null;
        foreach ($resources as $resource => $fields) {
            $r = $this->modx->getObject('modResource', array('pagetitle' => $resource));
            $this->assertInstanceOf('modResource', $r);
            $pagetitle = $r->get('pagetitle');
            $this->assertNotEmpty($pagetitle);
            /* see if parent, template, and TV Values are set properly */
            if ($pagetitle == 'utResource1') {
                $this->assertEquals($this->modx->getOption('default_template'), $r->get('template'));
                $this->assertEquals(0, $r->get('parent'));
                $id = $r->get('id');
            } elseif ($pagetitle == 'utResource2') {
                $templateObj = $this->modx->getObject('modTemplate',
                    array('templatename' => 'utTemplate1'));
                $templateId = $templateObj->get('id');
                $this->assertEquals($templateId, $r->get('template'));
                $this->assertEquals($id, $r->get('parent'));
                $this->assertEquals('SomeValue', $r->getTVValue('utTv1'));
                $this->assertEquals('SomeOtherValue', $r->getTVValue('utTv2'));

            } else {
                /* make sure pagetitles are set properly */
                assertTrue(false, 'BAD RESOURCE pagetitle');
            }
        }
    }
    public function testCreateBasics() {
        $this->mc->createBasics();
        $this->assertTrue(file_exists($this->mc->myPaths['targetRoot'] . '_build/build.transport.php'));
        $this->assertTrue(file_exists($this->mc->myPaths['targetRoot'] . '_build/build.config.php'));
        $this->assertTrue(is_dir($this->mc->myPaths['targetRoot'] . '_build/utilities'));
        $this->assertFalse(file_exists($this->mc->myPaths['targetRoot'] . '_build/utilities/config/' . $this->mc->packageNameLower . 'config.php'));
        $this->utHelpers->rrmdir($this->mc->myPaths['targetRoot']);
        $this->assertFalse(is_dir($this->mc->myPaths['targetRoot'] . '_build'));

        $this->mc->props['defaultStuff']['utilities'] = false;
        $this->mc->createBasics();
        $this->assertTrue(file_exists($this->mc->myPaths['targetRoot'] . '_build/build.transport.php'));
        $this->assertNotEmpty(file_get_contents($this->mc->myPaths['targetRoot'] . '_build/build.transport.php'));
        $this->assertTrue(file_exists($this->mc->myPaths['targetRoot'] . '_build/build.config.php'));
        $this->assertNotEmpty(file_get_contents($this->mc->myPaths['targetRoot'] . '_build/build.config.php'));

        $docs = array('readme.txt', 'tutorial.html', 'license.txt', 'changelog.txt' );
        foreach($docs as $doc) {
            $this->assertTrue(file_exists($this->mc->myPaths['targetCore'] . 'docs/' . $doc));
            $this->assertNotEmpty(file_get_contents($this->mc->myPaths['targetCore'] . 'docs/' . $doc));
        }
        $this->assertTrue(file_exists($this->mc->myPaths['targetRoot'] . 'readme.md'));
        $this->assertNotEmpty(file_get_contents($this->mc->myPaths['targetRoot'] . 'readme.md'));

        $this->assertNotEmpty($this->mc->props['languages']);
        $languages = $this->mc->props['languages'];
        foreach ($languages as $language => $files) {
            $fileNames = explode(',', $files);
            foreach ($fileNames as $fileName){
                $this->assertFileExists($this->mc->myPaths['targetCore'] . 'lexicon/' . $language . '/' . $fileName . '.inc.php', 'LANGUAGE: ' . $language . '  FILE: ' . $fileName . '.inc.php');
                $this->assertNotEmpty(file_get_contents($this->mc->myPaths['targetCore'] . 'lexicon/' . $language . '/' . $fileName . '.inc.php', 'LANGUAGE: ' . $language . '  FILE: ' . $fileName . '.inc.php'));
            }
        }
        $file = $this->mc->myPaths['targetBuild'] . 'utilities/' . 'jsmin.class.php';
        $this->assertTrue(file_exists($file), $file);
    }
    public function testCreateAssetsDirs() {
        $this->mc->createAssetsDirs();
        $this->assertFileExists($this->mc->myPaths['targetAssets'] . 'css/' . $this->mc->packageNameLower . '.css');
        $this->assertnotEmpty(file_get_contents($this->mc->myPaths['targetAssets'] . 'css/' . $this->mc->packageNameLower . '.css'));
        $this->assertFileExists($this->mc->myPaths['targetAssets'] . 'js/' . $this->mc->packageNameLower . '.js');
        $this->assertnotEmpty(file_get_contents($this->mc->myPaths['targetAssets'] . 'js/' . $this->mc->packageNameLower . '.js'));
    }
    public function testCreateResolvers() {


    }

    public function testCreateIntersects() {

    }




    public function testConnectSystemEventsToPlugins() {
        /* check connections */

        $this->mc->createElements();
        $this->mc->connectSystemEventsToPlugins();
        $plugins = $this->mc->props['elements']['modPlugin'];
        $this->assertNotEmpty($plugins);
        $plugins = explode(',',$plugins);
        foreach($plugins as $plugin) {
            /* @var $pluginObj modPlugin */
            /* @var $pluginEvent modPluginEvent */
            $alias = $this->mc->helpers->getNameAlias('modPlugin');
            $pluginObj = $this->modx->getObject('modPlugin', array ($alias => $plugin));
            $this->assertInstanceOf('modPlugin', $pluginObj);
            $events = $this->mc->props['pluginEvents'][$plugin];
            $this->assertNotEmpty($events);
            $events = explode(',', $events);
            foreach ($events as $event) {
                if (strstr($event, ':')) {
                    $data = explode(':', $event);
                    $event = $data[0];
                    $priority = $data[1];
                } else {
                    $priority = 0;
                }
                $fields = array (
                    'pluginid' => $pluginObj->get('id'),
                    'event' => $event,
                );
                $eventName = $this->modx->getObject('modEvent', array('name' => $event));
                $this->assertInstanceOf('modEvent', $eventName, 'EVENT NAME: ' . $event);
                if (strstr($this->mc->props['newSystemEvents'],$event)) {
                    /* new event */
                    $this->assertEquals($eventName->get('groupname'), $this->mc->props['category']);
                }
                $pluginEvent = $this->modx->getObject('modPluginEvent', $fields);
                $this->assertInstanceOf('modPluginEvent', $pluginEvent);
                $this->assertEquals($priority, $pluginEvent->get('priority'));
            }
        }

        /* check creation of plugin resolver */

        $fileName = $this->mc->targetBase . '_build/resolvers/plugin.resolver.php';
        $this->assertFileExists($fileName);
        $content = file_get_contents($fileName);
        $this->assertNotEmpty($content);

        /* make sure all placeholders got replaced */
        $this->assertEmpty(strstr($content, '[[+'));
        $this->assertNotEmpty(strstr($content, 'License'));

        $names = $this->mc->props['newSystemEvents'];
        $this->assertNotEmpty(strstr($content, $names) . "NAMES: " . $names);

        /* remove event names from system_eventnames */
        /* @var $eventName modEvent */
        $names = empty($names) ? array() : explode(',', $names);
        foreach ($names as $name) {
            $eventName = $this->modx->getObject('modEvent', array('name' => $name));
            if ($eventName) {
                $eventName->remove();
            }
        }
    }

    public function testConnectTvsToTemplates()
    {
        $this->mc->createElements();
        $this->mc->connectTvsToTemplates();
        $templateVarTemplates = $this->modx->getOption('templateVarTemplates', $this->mc->props, array());

        /* check connection */
        $templateId = null;
        $tvId = null;
        $this->assertNotEmpty($templateVarTemplates);
        foreach ($templateVarTemplates as $templateName => $tvNames) {
            $this->assertNotEmpty($templateName);
            $this->assertNotEmpty($tvNames);
            if ($templateName == 'default') {
                $templateId = $this->modx->getOption('default_template', null, null);
                $templateObj = $this->modx->getObject('modTemplate', (integer)$templateId);
            } else {
                $alias = $this->utHelpers->getNameAlias('modTemplate');
                $templateObj = $this->modx->getObject('modTemplate', array($alias => $templateName));
                $this->assertInstanceOf('modTemplate', $templateObj);
                $templateId = $templateObj->get('id');

            }
            $this->assertNotNull($templateId);
            $tvs = explode(',', $tvNames);
            $this->assertNotEmpty($tvs);
            foreach ($tvs as $tvName) {
                $this->assertTrue($templateId !== null);
                $this->assertNotEmpty($tvName);
                $alias = $this->utHelpers->getNameAlias('modTemplateVar');
                $tvObj = $this->modx->getObject('modTemplateVar', array($alias => $tvName));
                $this->assertInstanceOf('modTemplate', $templateObj);
                $this->assertInstanceOf('modTemplateVar', $tvObj);
                /* @var $tvObj modTemplateVar */
                /* @var $templateObj modTemplate */
                /* @var $tvt modTemplateVarTemplate */

                $tvId = $tvObj->get('id');
                $this->assertTrue($tvId !== null);
                $fields = array(
                    'templateid' => $templateObj->get('id'),
                    'tmplvarid' => $tvObj->get('id'),
                );
                $tvt = $this->modx->getObject('modTemplateVarTemplate',$fields);
                $this->assertInstanceOf('modTemplateVarTemplate', $tvt, 'Template: ' . $templateObj->get('templatename') . ' --  TV: ' . $tvObj->get('name'));

            }
        }
        /* check for resolver */
        $this->assertFileExists($this->mc->targetBase . '_build/resolvers/tv.resolver.php');
        $content = file_get_contents($this->mc->targetBase . '_build/resolvers/tv.resolver.php');
        $this->assertNotEmpty($content);
        $this->assertNotEmpty(strstr($content,'License'));
        /* make sure all placeholders got replaced */
        $this->assertEmpty(strstr($content, '[[+'));
    }
    public function testConnectResourcesToTemplates() {
        $this->mc->createElements();
        $this->mc->createResources();
        $this->mc->connectResourcesToTemplates();
        $ResourceTemplates = $this->modx->getOption('resourceTemplates', $this->mc->props, '');
        $this->assertNotEmpty($ResourceTemplates);
        foreach ($ResourceTemplates as $templateName => $resourceList) {
            $this->assertNotEmpty($templateName);
            $this->assertNotEmpty($resourceList);
            $resources = explode(',', $resourceList);

            $alias = $this->utHelpers->getNameAlias('modTemplate');
            $templateObj = $this->modx->getObject('modTemplate', array($alias => $templateName));

            $this->assertInstanceOf('modTemplate', $templateObj);
            foreach ($resources as $resourcePagetitle) {
                $alias = $this->utHelpers->getNameAlias('modResource');
                $resourceObj = $this->modx->getObject('modResource', array($alias => $resourcePagetitle ));
                $this->assertInstanceOf('modResource', $resourceObj);

                $this->assertEquals($templateObj->get('id'), $resourceObj->get('template'));

            }
        }

        /* check for resolver */
        $this->assertFileExists($this->mc->targetBase . '_build/resolvers/resource.resolver.php');
        $content = file_get_contents($this->mc->targetBase . '_build/resolvers/resource.resolver.php');
        $this->assertNotEmpty($content);
        $this->assertNotEmpty(strstr($content, 'License'));
        /* make sure all placeholders got replaced */
        $this->assertEmpty(strstr($content, '[[+'));

    }
    public function testCreateValidators()
    {
        $this->mc->createValidators();
        $validators = $this->mc->props['validators'];
        $this->assertNotEmpty($validators);

        foreach ($validators as $validator) {
            $validator = $validator == 'default'? $this->mc->packageNameLower : $validator;
            $this->assertFileExists($this->mc->myPaths['targetRoot'] . '_build/validators/' . $validator . '.validator.php');
            $this->assertNotEmpty(file_get_contents($this->mc->myPaths['targetRoot'] . '_build/validators/' . $validator . '.validator.php'));

        }
    }

    public function testCreateExtraResolvers()
    {
        $this->mc->createExtraResolvers();
        $resolvers = $this->mc->props['resolvers'];
        $this->assertNotEmpty($resolvers);
        foreach ($resolvers as $resolver) {
            $resolver = $resolver == 'default' ? $this->mc->packageNameLower : $resolver;
            $this->assertFileExists($this->mc->myPaths['targetRoot'] . '_build/resolvers/' . $resolver . '.resolver.php');
            $this->assertNotEmpty(file_get_contents($this->mc->myPaths['targetRoot'] . '_build/resolvers/' . $resolver . '.resolver.php'));

        }
    }
    public function testCreateInstallOption () {
        $this->mc->createInstallOptions();
        $this->assertFileExists($this->mc->myPaths['targetRoot'] . '_build/install.options/user.input.php');
        $this->assertNotEmpty(file_get_contents($this->mc->myPaths['targetRoot'] . '_build/install.options/user.input.php'));
    }


    public function testConnectPropertySetsToElements() {
        $this->mc->createPropertySets();
        $this->mc->createElements();
        $this->mc->connectPropertySetsToElements();
        $propertySets = $this->mc->props['propertySetElements'];
        $this->assertNotEmpty($propertySets);
        $this->modx->log(MODX::LOG_LEVEL_INFO, '    Connecting ' . count($propertySets) . ' Property Sets to Elements');

        foreach ($propertySets as $propertySetName => $elements) {
            $alias = $this->mc->helpers->getNameAlias('modPropertySet');
            $propertySetObj = $this->modx->getObject('modPropertySet', array($alias => $propertySetName));
            $this->assertInstanceOf('modPropertySet', $propertySetObj);

            $els = empty($elements) ? array() : explode(',', $elements);
            foreach ($els as $el) {
                $data = explode(':', $el);
                $elementName = trim($data[0]);
                $elementType = trim($data[1]);
                $alias = $this->mc->helpers->getNameAlias($elementType);
                $elementObj = $this->modx->getObject($elementType, array($alias => $elementName));
                $this->assertInstanceOf($elementType,$elementObj);

                /* @var $elementObj modElement */
                /* @var $propertySetObj modPropertySet */
                /* @var $elementPropertySet modElementPropertySet */
                $elementId = $elementObj->get('id');
                $propertySetId = $propertySetObj->get('id');
                $elementPropertySet = $this->modx->getObject('modElementPropertySet', array(
                    'element' => $elementId,
                    'property_set' => $propertySetId,
                ));
                $this->assertInstanceOf('modElementPropertySet',$elementPropertySet);
            }

        }
        /* check for resolver */
        $dir = $this->mc->targetBase . '_build/resolvers';
        $fileName = 'propertyset.resolver.php';
        $this->assertFileExists($dir . '/' . $fileName);

        $content = file_get_contents($dir . '/' . $fileName);
        $this->assertNotEmpty($content);
        /* check for license */
        $this->assertNotEmpty(strstr($content, 'License'));
        /* make sure all placeholders got replaced */
        $this->assertEmpty(strstr($content, '[[+'));
    }

    public function testCreateClassFiles() {
        $this->utHelpers->rrmdir($this->mc->targetCore . '/model');
        $this->mc->createClassFiles();
        $classes = $this->mc->props['classes'];
        $this->assertNotEmpty($classes);
        $baseDir = $this->mc->targetCore . 'model';
        foreach ($classes as $className => $data) {
            $data = explode(':', $data);
            if (!empty($data[1])) {
                $dir = $baseDir . '/' . $data[0] . '/' . $data[1];
            } else { /* no directory */
                $dir = $baseDir . '/' . $data[0];
            }
            $fileName = strtolower($className) . '.class.php';
            $this->assertTrue(is_dir($dir));
            $this->assertFileExists($dir . '/' . $fileName);
            $this->assertNotEmpty(file_get_contents($dir . '/' . $fileName));
            $content = file_get_contents($dir . '/' . $fileName);
            /* check for constructor */
            $this->assertNotEmpty(strstr($content, '__construct'));
            /* check class name */
            $this->assertNotEmpty(strstr($content, 'class ' . $className));
            /* check for license */
            $this->assertNotEmpty(strstr($content, 'License'));
            /* make sure all placeholders got replaced */
            $this->assertEmpty(strstr($content, '[[+'));
        }

    }
    public function testHelpers() {
        $dir = $this->mc->myPaths['targetCore'] . '/dummy/dummy';
        $fileName = 'dummy.php';
        $this->assertFileNotExists($dir .'/' . $fileName);
        $this->mc->helpers->writeFile($dir, $fileName, 'Something');
        $this->assertFileExists($dir . '/' . $fileName);
        $this->assertEquals(file_get_contents($dir . '/' . $fileName), 'Something');
        $this->utHelpers->rrmdir($this->mc->myPaths['targetRoot']);
        $this->assertFileNotExists($dir . '/' . $fileName);

        /* test removeElements */
        $this->utHelpers->removeElements($this->modx, $this->mc);
        $this->mc->createElements();
        $this->utHelpers->removeElements($this->modx, $this->mc);
        $elements = $this->mc->props['elements'];
        foreach ($elements as $elementType => $elementNames) {
            $alias = $this->mc->helpers->getNameAlias($elementType);
            $elementNames = empty($elementNames)? array() : explode(',', $elementNames);
            foreach($elementNames as $elementName) {
                $obj = $this->modx->getObject($elementType, array($alias => $elementName));
                $this->assertNull($obj);
            }
        }
        /* test removeResources */
        $this->mc->createResources();
        $this->utHelpers->removeResources($this->modx, $this->mc);
        $resources = $this->mc->props['resources'];
        $resources = explode(',', $resources);
        foreach ($resources as $resource) {
            $r = $this->modx->getObject('modResource', array('pagetitle' => $resource));
            $this->assertNull($r);
        }
        /* test removePropertySets (CRASHES PhpStorm - createPropertySets() doesn't exist */

        /*$this->mc->createPropertySets();
        $this->utHelpers->removePropertySets($this->modx, $this->mc);
        $sets = $this->mc->props['elements']['propertySets'];
        $this->assertNotEmpty($sets);
        foreach ($sets as $set => $fields) {
            $alias = $this->mc->helpers->getNameAlias('modPropertySet');
            $setObj = $this->modx->getObject('modPropertySet', array($alias => $set));
            $this->assertNull($setObj);
        }*/
    }
}