<?php

/**
 * Test class for MyComponentProject Bootstrap.
 * Generated by PHPUnit on 2012-03-02 at 23:02:19.
 * @outputBuffering disabled
 */

class LexiconCodeFileTest extends PHPUnit_Framework_TestCase {

    /* @var $mc MyComponentProject */
    public $mc;
    /* @var $modx modX */
    public $modx;
    /* @var $utHelpers UtHelpers */
    public $utHelpers;
    /* @var $lcf LexiconCodeFile;
     * */
    public $lcf;
    /**
     * @var $root string - target root
     */
    public $rootDir;
    /**
     * @var $lexDir string - target lexicon directory
     */
    public $lexDir;
    /**
     * @var $coreDir string - target core directory
     */
    public $coreDir;
    /**
     * @var $modelDir string - target model directory
     */
    public $modelDir;

    /**
     * @var $jsDir string - target JS directory
     */
    public $jsDir;

    /**
     * @var $chunkDir string - target chunks directory
     */
    public $chunkDir;
    /**
     * @var $dataDir string - directory with mock files to copy
     */
    public $dataDir;

    /** @var  $languages array */
    public $languages;






    protected function setUp() {
        require_once dirname(__FILE__) . '/build.config.php';
        require_once dirname(__FILE__) . '/uthelpers.class.php';
        require_once MODX_CORE_PATH . 'model/modx/modx.class.php';
        $this->utHelpers = new UtHelpers();
        $modx = new modX();
        $this->modx =& $modx;
        $modx->initialize('mgr');
        $modx->getService('error', 'error.modError', '', '');
        $modx->getService('lexicon', 'modLexicon');
        $modx->getRequest();
        $homeId = $modx->getOption('site_start');
        $homeResource = $modx->getObject('modResource', $homeId);

        if ($homeResource instanceof modResource) {
            $modx->resource = $homeResource;
        } else {
            echo "\nNo Resource\n";
        }

        $modx->setLogLevel(modX::LOG_LEVEL_ERROR);
        $modx->setLogTarget('ECHO');

        require_once MODX_ASSETS_PATH . 'mycomponents/mycomponent/core/components/mycomponent/model/mycomponent/mycomponentproject.class.php';

        /* @var $categoryObj modCategory */
        $this->mc = new MyComponentProject($modx);
        $this->mc->init(array(), 'example');
        $this->dataDir = dirname(__FILE__) . '/data/';
        $this->dataDir = str_replace('\\', '/', $this->dataDir);


        $this->rootDir = dirname(dirname(dirname(dirname(__FILE__)))) . '/unittest/';
        $this->rootDir = str_replace('\\', '/', $this->rootDir);
        $this->rootDir = strtolower($this->rootDir);
        $this->utHelpers->rrmdir($this->rootDir);
        @mkdir($this->rootDir, '0644', true);

        $this->coreDir = $this->rootDir . 'core/components/unittest/';
        @mkdir($this->coreDir, '0644', true);
        $this->coreDir = str_replace('\\', '/', $this->coreDir);

        $this->lexDir = $this->coreDir . 'lexicon/';
        $this->lexDir = str_replace('\\', '/', $this->lexDir);
        @mkdir($this->lexDir . 'en', '0644', true);
        copy($this->dataDir . 'default.inc.php',
        $this->lexDir . 'en/default.inc.php');

        $this->modelDir = $this->coreDir . 'model/';
        $this->modelDir = str_replace('\\', '/', $this->modelDir);
        @mkdir($this->modelDir, '0644', true);
        copy($this->dataDir . 'example.class.php',
        $this->modelDir . 'example.class.php');

        $this->jsDir = $this->rootDir . 'assets/components/unittest/js/';
        $this->jsDir = str_replace('\\', '/', $this->jsDir);
        @mkdir($this->jsDir, '0644', true);
        copy($this->dataDir . 'example.js',
        $this->jsDir . 'example.js');

        $this->chunkDir = $this->coreDir . 'elements/chunks/';
        $this->chunkDir = str_replace('\\', '/', $this->chunkDir);
        @mkdir($this->chunkDir, '0644', true);
        copy($this->dataDir . 'chunk1.chunk.html',
        $this->chunkDir . 'chunk1.chunk.html');

        $this->languages = array(
            'en' => array(
                'default',
                'properties',
                'forms',
            ),
        );

        $this->assertNotEmpty($this->rootDir, 'Empty Root');
        $this->assertNotEmpty($this->coreDir, 'Empty target core');
        $this->assertNotEmpty($this->lexDir, 'Empty target lex dir');
        $this->assertNotEmpty($this->modelDir, 'Empty Model dir');
        $this->assertNotEmpty($this->jsDir, 'Empty JS dir');
        $this->assertNotEmpty($this->chunkDir, 'Empty chunk dir');
    }

    protected function tearDown() {
        // $this->utHelpers->rrmdir($this->rootDir);
    }

    public function testSetup() {
        // echo $this->coreDir;
    }

    public function testSetLexFiles() {
        $lcf = new LexiconCodeFile($this->modx, $this->mc->helpers,
            $this->modelDir, 'example.class.php', $this->lexDir, $this->languages);
        $language = $lcf->language;
        $this->assertNotEmpty($language);

        $lexFiles = $lcf->getLexFiles();
        $expected = array(
            $this->lexDir . $language . '/default.inc.php' => 'default.inc.php'
        );

            $this->assertNotEmpty($lexFiles);
        $this->assertEquals($expected, $lexFiles);

        $lcf->addLexfile('properties');

        $lexFiles = $lcf->getLexFiles();

        $expected = array(
            $this->lexDir . $language . '/default.inc.php' => 'default.inc.php',
            $this->lexDir . $language . '/properties.inc.php' => 'properties.inc.php'
        );
        $this->assertNotEmpty($lexFiles);
        $this->assertEquals($expected, $lexFiles);

        /* Test with no lexicon load line */
        $lcf = null;


        $lcf = new LexiconCodeFile($this->modx, $this->mc->helpers,
            $this->chunkDir, 'chunk1.chunk.html', $this->lexDir, $this->languages);
        $lexFiles = $lcf->getLexFiles();
        $expected = array(
            $this->lexDir . $language . '/default.inc.php' => 'default.inc.php',
        );
        $this->assertNotEmpty($lexFiles);
        $this->assertEquals($expected, $lexFiles);
    }

    /** Test getting lex strings from php file, js file, and Tpl chunk */
    public function testSetUsed() {
        $files = array(
            $this->modelDir => 'example.class.php',
            $this->jsDir => 'example.js',
            $this->chunkDir => 'chunk1.chunk.html',
        );
        foreach ($files as $dir => $fileName) {
            $lcf = null;
            $this->assertFileExists($dir . '/' . $fileName);
            $lcf = new LexiconCodeFile($this->modx, $this->mc->helpers,
                $dir, $fileName, $this->lexDir, $this->languages);
            $lexStrings = $lcf->getUsed();
            $this->assertTrue(is_array($lexStrings));
            $this->assertNotEmpty($lexStrings);
            $this->assertTrue(array_key_exists('string1', $lexStrings));
            $this->assertTrue(array_key_exists('string2', $lexStrings));
            $this->assertTrue(array_key_exists('string3', $lexStrings));
            $this->assertEquals($lexStrings['string1'], 'Hello \'columbus\'', $fileName);
            $this->assertEquals($lexStrings['string2'], 'Hello "columbus"');
        }
    }

    public function testSetMissing() {
        $files = array(
            $this->modelDir => 'example.class.php',
            $this->jsDir => 'example.js',
            $this->chunkDir => 'chunk1.chunk.html',
        );
        foreach ($files as $dir => $fileName) {
            $lcf = null;
            $this->assertFileExists($dir . '/' . $fileName);
            $lcf = new LexiconCodeFile($this->modx, $this->mc->helpers,
                $dir, $fileName, $this->lexDir, $this->languages);
            $lexStrings = $lcf->getUsed();
            $missing = $lcf->getMissing();
            $toUpdate = $lcf->getToUpdate();

            $this->assertTrue(is_array($lexStrings));
            $this->assertNotEmpty($lexStrings, $fileName);
            $this->assertTrue(is_array($missing));
            $this->assertNotEmpty($missing);
            $this->assertTrue(is_array($toUpdate));
            $this->assertNotEmpty($toUpdate);


            $this->assertTrue(array_key_exists('string1', $missing));
            $this->assertTrue(array_key_exists('string3', $missing));
            $this->assertEquals('Hello \'columbus\'', $lexStrings['string1']);
            $this->assertEquals('Hello "columbus"', $lexStrings['string2']);

            $expected = array(
                'string2' => 'Hello "columbus"',
                'string4' => 'Updated String',
            );
            if ($fileName == 'chunk1.chunk.html') {
                $this->assertEquals($expected, $toUpdate);
            }
        }
    }

    public function testUpdateLexiconFile() {
        $_lang = array();
        $path = $this->lexDir . 'en/default.inc.php';
        include $path;
        $this->assertNotEmpty($_lang);
        $expected = array(
            'string2' => 'String2 in Lexicon file',
            'string4' => 'String4 in Lexicon file',
            'unused' => 'Unused Lexicon String',
            'empty_string' => '',
        );
        $this->assertEquals($expected, $_lang);

        $files = array(
            $this->modelDir => 'example.class.php',
            $this->jsDir => 'example.js',
            $this->chunkDir => 'chunk1.chunk.html',
        );
        foreach ($files as $dir => $fileName) {
            $lcf = null;
            $this->assertFileExists($dir . '/' . $fileName);
            $lcf = new LexiconCodeFile($this->modx, $this->mc->helpers,
                $dir, $fileName, $this->lexDir, $this->languages);
            $lcf->updateLexiconFile();
            $_lang = array();
            include $path;
            $this->assertNotEmpty($_lang);
            switch ($fileName) {
                case 'example.class.php':
                    $this->assertEquals('Hello "columbus"', $_lang['string2']);
                    $this->assertEquals('Hello \'columbus\'', $_lang['string4']);
                    $this->assertEquals('Unused Lexicon String', $_lang['unused']);
                    $this->assertEquals('', $_lang['empty_string']);
                    $this->assertEquals('Hello \'columbus\'', $_lang['string1']);
                    $this->assertEquals('', $_lang['string3']);
                    break;
                case 'example.js':
                    break;
                case 'chunk1.chunk.html':
                    $this->assertEquals('Updated String', $_lang['string4']);
                    $this->assertEquals('Updated Empty string', $_lang['string3']);
                    break;
                default:
                    assertTrue(false);
            }
        }
    }

    public function testUpdateCodeFile() {
        $files = array(
            $this->modelDir => 'example.class.php',
            $this->jsDir => 'example.js',
            $this->chunkDir => 'chunk1.chunk.html',
        );
        foreach ($files as $dir => $fileName) {
            $lcf = null;
            $this->assertFileExists($dir . '/' . $fileName);
            $lcf = new LexiconCodeFile($this->modx, $this->mc->helpers,
                $dir, $fileName, $this->lexDir, $this->languages);
            $updated = $lcf->updateCodeFile();

            $content = file_get_contents($dir .'/' . $fileName);
            $this->assertNotEmpty($content, 'File content is empty');

            if ($fileName == 'example.class.php') {
                $this->assertTrue(strpos($content, '~~') === false, '~~ found', $fileName);
                $this->assertContains('$x = $this->modx->lexicon("string1")', $content);
                $this->assertContains('$y = $this->modx->lexicon(\'string2\')', $content);
                $this->assertContains('$z = $this->modx->lexicon(\'string3\')', $content);
            }
            if ($fileName == 'chunk1.chunk.html') {
                $this->assertTrue(strpos($content, '~~') === false, '~~ found', $fileName);
                $this->assertContains('[[%string1]]', $content);
                $this->assertContains('[[%string2]]', $content);
                $this->assertContains('[[%string3]]', $content);
            }
            if ($fileName == 'example.js') {
                $this->assertContains('x = _("string1")', $content);
                $this->assertContains('y = _(\'string2\')', $content);
                $this->assertContains('z = _(\'string3\')', $content);
            }
        }
    }

}
