<?php

  $projects = array (
  'cacheclear' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/cacheclear.config.php',
  'cachemaster' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/cachemaster.config.php',
  'canonical' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/canonical.config.php',
  'caseinsensitiveurls' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/caseinsensitiveurls.config.php',
  'chimpsync' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/chimpsync.config.php',
  'classextender' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/classextender.config.php',
  'defaultresourcegroup' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/defaultresourcegroup.config.php',
  'defaultusergroup' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/defaultusergroup.config.php',
  'dirwalker' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/dirwalker.config.php',
  'dottest' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/dottest.config.php',
  'emptyalias' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/emptyalias.config.php',
  'example' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/example.config.php',
  'example2' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/example2.config.php',
  'flexibility4' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/flexibility4.config.php',
  'foryourapproval' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/foryourapproval.config.php',
  'fwa' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/fwa.config.php',
  'hhc' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/hhc.config.php',
  'importusers' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/importusers.config.php',
  'loglogins' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/loglogins.config.php',
  'mandrillx' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/mandrillx.config.php',
  'moveresources' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/moveresources.config.php',
  'mycomponent' => 'c:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/mycomponent.config.php',
  'newspublisher' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/newspublisher.config.php',
  'notify' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/notify.config.php',
  'orphans' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/orphans.config.php',
  'privatepage' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/privatepage.config.php',
  'propertiestest' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/propertiestest.config.php',
  'refreshcache' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/refreshcache.config.php',
  'season' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/season.config.php',
  'showtv' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/showtv.config.php',
  'sitecheck' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/sitecheck.config.php',
  'stagecoach' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/stagecoach.config.php',
  'subscribe' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/subscribe.config.php',
  'unittest' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/unittest.config.php',
  'usermanagement' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/usermanagement.config.php',
  'userphotos' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/userphotos.config.php',
  'gorevo' => 'C:/xampp/htdocs/addons/assets/mycomponents/mycomponent/_build/config/gorevo.config.php',
);
 return $projects;